# Generated by Django 5.0.6 on 2024-07-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submodel",
            options={
                "permissions": [
                    ("enterprise", "Enterprise Perm"),
                    ("standard", "Standard Perm"),
                    ("free", "Free Perm"),
                    ("AI free", "Free Perm"),
                    ("AI Advance", "Free Perm"),
                ]
            },
        ),
        migrations.AddField(
            model_name="submodel",
            name="groups",
            field=models.ManyToManyField(blank=True, to="auth.group"),
        ),
        migrations.AddField(
            model_name="submodel",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "codename_in": [
                        "enterprise",
                        "standard",
                        "free",
                        "AI free",
                        "AI Advance",
                    ],
                    "content_type__app_label": "subscriptions",
                },
                to="auth.permission",
            ),
        ),
    ]
