# Generated by Django 5.0.6 on 2024-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0002_alter_submodel_options_submodel_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submodel",
            options={
                "permissions": [
                    ("enterprise", "Enterprise Perm"),
                    ("standard", "Standard Perm"),
                    ("free", "Free Perm"),
                    ("ai_free", "Free AI Perm"),
                    ("ai_adv", "Advance AI Perm"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="submodel",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "codename_in": [
                        "enterprise",
                        "standard",
                        "free",
                        "ai_free",
                        "ai_adv",
                    ],
                    "content_type__app_label": "subscriptions",
                },
                to="auth.permission",
            ),
        ),
    ]
