# Generated by Django 5.0.6 on 2024-07-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("subscriptions", "0003_alter_submodel_options_alter_submodel_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="submodel",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="submodel",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "codename__in": [
                        "enterprise",
                        "standard",
                        "free",
                        "ai_free",
                        "ai_adv",
                    ],
                    "content_type__app_label": "subscriptions",
                },
                to="auth.permission",
            ),
        ),
    ]
