# Generated by Django 5.0.6 on 2024-07-11 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0006_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserSubscription",
        ),
    ]
