# TODO: ADD WHITENOSE LATER
# TODO: ADD NECESSARY CHANGES TO THE DOCKERFILE
# TODO: MAKES CHANGES ON THE RAILWAY PLATFORM FOR THE DOCKER DEOPLOYMENT
# TODO: MAKE CHANGES FOR THE EMAIL IN DEV.NEURONS.GMAIL.COM
